### ISSUE TITLE
train error 

### ISSUE THREAD

**Issue by walton-wang929** [open-mmlab/mmaction#16]
when i use i3d_kinetics_3d_rgb_r50_c3d_inflate3x1x1_seg1_f32s2_b8_g8_imagenet this config to reproduce the kinetics result, this comes to an error :

```
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "./tools/train_recognizer.py", line 90, in <module>
    main()
  File "./tools/train_recognizer.py", line 86, in main
    logger=logger)
  File "/home/wangtao1/mmaction/mmaction/apis/train.py", line 57, in train_network
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/wangtao1/mmaction/mmaction/apis/train.py", line 102, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/site-packages/mmcv/runner/runner.py", line 356, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mmcv/runner/runner.py", line 262, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/wangtao1/mmaction/mmaction/apis/train.py", line 37, in batch_processor
    loss, log_vars = parse_losses(losses)
  File "/home/wangtao1/mmaction/mmaction/apis/train.py", line 30, in parse_losses
    log_vars[name] = log_vars[name].item()
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /pytorch/aten/src/THC/THCCachingAllocator.cpp:470)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f719f2e6021 in /usr/local/lib64/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f719f2e58ea in /usr/local/lib64/python3.6/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x13f6002 (0x7f70fffed002 in /usr/local/lib64/python3.6/site-packages/torch/lib/libcaffe2_gpu.so)
frame #3: at::TensorImpl::release_resources() + 0x50 (0x7f70f5433440 in /usr/local/lib64/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #4: <unknown function> + 0x2af03b (0x7f7197d5003b in /usr/local/lib64/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #5: <unknown function> + 0x3174e3 (0x7f7197db84e3 in /usr/local/lib64/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #6: torch::autograd::deleteFunction(torch::autograd::Function*) + 0x198 (0x7f7197d52878 in /usr/local/lib64/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #7: std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() + 0x45 (0x7f719f6050f5 in /usr/local/lib64/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #8: torch::autograd::Variable::Impl::release_resources() + 0x4a (0x7f7197fc2d5a in /usr/local/lib64/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #9: <unknown function> + 0x124cfb (0x7f719f61bcfb in /usr/local/lib64/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x3204af (0x7f719f8174af in /usr/local/lib64/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0x3204f1 (0x7f719f8174f1 in /usr/local/lib64/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #28: main + 0x119 (0x400a99 in /usr/bin/python3)
frame #29: __libc_start_main + 0xf5 (0x7f71aeb9a3d5 in /lib64/libc.so.6)
frame #30: /usr/bin/python3() [0x400c20]
```
 anynone knows what is wrong?

**Comment by zhaoyue-zephyrus** [comment]
@walton-wang929  What is your script for training? Did you modify anything? One possible cause could be that certain sample label is out of the range of the `num_classes` for the classification head.

**Comment by walton-wang929** [comment]
I used i3d_kinetics400_3d_rgb_r50_c3d_inflate3x1x1_seg1_f32s2.py this configure. coz the whole dataset I haven't downloaded. just use a part of kinetics. maybe I wait for all knietics dataset is ready ,then I try again.

**Comment by walton-wang929** [comment]
@zhaoyue-zephyrus another question, when i reproduce UCF-101 experiments, I found the result was worse than model zoo released.  the details are here. this issue has been closed.
[Reproduction of 2D TSN experiment on RGB images (UCF101) #13](https://github.com/open-mmlab/mmaction/issues/13)

**Comment by walton-wang929** [comment]
I found the problem, the configuration was wrong.
